### ISSUE TITLE
Crash on Kill - DllNotFoundException "libMonoPosixHelper.so"

### ISSUE THREAD

**Issue by khionu** [hamstar0/tml-rewards-mod#36]
https://gist.github.com/af3849b1b81f939e62b7be83006a00b4

**Comment by khionu** [comment]
Umm... why was this closed? Was this fixed? Can't reproduce?

**Comment by hamstar0** [comment]
> Umm... why was this closed? Was this fixed? Can't reproduce?

It looks like the error has something to do with saving binary data from Mod Helpers. You might be able to fix this by changing the config setting `DebugModeSaveKillsAsJson` to true, but you'll lose your character's current PP accumulation.

**Comment by khionu** [comment]
Well, I'll test after the rewrite, then.
